# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d01be85b11fed657dd32d923b3f0e0fb4446fbe555a9d146c9637a76d20d08e739c48d42633b43a5c1b0a0ef1cd3aa8376bdfa67d3b37be5fd1665adc8cbeb12

test:
  secret_key_base: 5b653128651f153932f6771180ceb550ddeb18906f634851aec93fa028c25cd47fee26dc527de21e609f0566f39b20cf7ee323300f0c6887ceccdc2f62c3702e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
